// AUTO-GENERATED by scripts/generate-emotion-manifest.js — do not edit by hand.
// Add FER2013 images to assets/emotions/<emotion>/ and run: npm run emotions:manifest
import type { ImageSourcePropType } from 'react-native';

import type { Emotion } from '@/types/emotion';

export type EmotionPhotoEntry = {
  id: string;
  emotion: Emotion;
  difficulty: 1 | 2 | 3;
  source: ImageSourcePropType;
};

export const emotionPhotoManifest: EmotionPhotoEntry[] = [];
